local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "enUS", true)

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Auto Position Castbar"
L["AUTO_POS_BAR_TOOLTIP"] = [=[When enabled it will auto position the castbar based on things like how many buffs are shown on the unit frame and so on.

Does not work with third-party unit frames.]=]
L["BORDER_COLOR"] = "Select Border Color"
L["BORDERSHIELD"] = "Show Uninterruptible Border Shield"
L["BORDERSHIELD_TOOLTIP"] = [=[Shows a shield around the castbar when a cast cannot be interrupted. Disabling this option will still show a grey background color on uninterruptible casts.

|cffffff00You can click the "Toggle Testing Castbar" button while holding down any modifier keys like SHIFT or CTRL to test the castbar with border shield shown.|r
]=]
L["CAST_BORDER"] = "Select Border Texture"
L["CAST_BORDER_TOOLTIP"] = "Select texture used for castbar border."
L["CAST_FONT"] = "Select Castbar Font"
L["CAST_FONT_TOOLTIP"] = "Select font type used for spell name and timer text."
L["CAST_STATUSBAR"] = "Select Castbar Texture"
L["CAST_STATUSBAR_TOOLTIP"] = "Select texture type used for the castbar/statusbar."
L["CASTBAR"] = "Castbar"
L["CASTBAR_COLORS"] = "Castbar Colors"
L["CASTBAR_ICON"] = "Castbar Icon"
L["CASTBAR_SIZING"] = "Castbar Sizing"
L["CASTBAR_TEXTURE_FONT"] = "Castbar Textures"
L["DEFAULT"] = "Default"
L["FONT_SIZE"] = "Font Size"
L["FONT_SIZE_TOOLTIP"] = "Sets font size used for spell name and timer text."
L["FRAME_LEVEL"] = "Frame Level"
L["FRAME_LEVEL_DESC"] = "Change frame level to layer the castbar below or above another frame."
L["GENERAL"] = "General Settings"
L["HEIGHT"] = "Castbar Height"
L["HEIGHT_TOOLTIP"] = "Sets the castbar height."
L["ICON_HIDE_BORDER"] = "Hide Icon Border"
L["ICON_POS_X"] = "Icon Position X"
L["ICON_POS_Y"] = "Icon Position Y"
L["ICON_SHOW"] = "Show Spell Icon"
L["ICON_SIZE"] = "Icon Size"
L["ICON_SIZE_TOOLTIP"] = "Sets the size for the castbar spell icon."
L["LSM_TEXTURE_NOTE"] = [=[

Note: If you use a custom third-party texture/font and delete it later on from your PC, you'll need to manually reset the texture or font here for the addon to continue working.]=]
L["NAMEPLATE"] = "Nameplate"
L["PARTY"] = "Party"
L["PER_CHARACTER"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tCharacter Specific Settings"
L["PER_CHARACTER_TOOLTIP"] = "Click this to toggle between general settings and settings specific to this character."
L["PLAYER"] = "Player"
L["POSXY_TOOLTIP"] = "Adjust the XY offset values to move the frame."
L["REQUIRES_RESTART"] = "Toggling this castbar module requires a reload of your interface. Press Accept to reload UI."
L["RESET_ALL"] = "Reset All Settings"
L["SHOW_FOR_ENEMY"] = "Show Enemy Casts"
L["SHOW_FOR_FRIENDLY"] = "Show Friendly Casts"
L["SHOW_SPARK"] = "Show Castbar Spark Effect"
L["SHOW_TIMER"] = "Show Timer Text"
L["SHOW_TIMER_TOOLTIP"] = "Display a timer countdown for the current cast."
L["STATUS_BG_COLOR"] = "Select Background Color"
L["STATUS_CHANNEL_COLOR"] = "Select Channel Fill Color"
L["STATUS_COLOR"] = "Select Cast Fill Color"
L["STATUS_FAILED_COLOR"] = "Select Cast Failed Fill Color"
L["STATUS_UNINTERRUPTIBLE_COLOR"] = "Select Uninterruptible Fill Color"
L["TARGET"] = "Target"
L["TEST"] = "Toggle Testing"
L["TEST_MODE_DRAG"] = "Test Mode - Drag To Move"
L["TEST_PLATE_TOOLTIP"] = [=[Show the nameplate castbar for testing. You can drag the castbar to move it.
You'll need to target someone and have the nameplate be visible to see the test castbar.
]=]
L["TEST_TARGET_TOOLTIP"] = [=[Show the target frame castbar for testing. You can drag the castbar to move it.
You'll need to target someone first to see the test castbar.
]=]
L["TEXT_COLOR"] = "Select Text Color"
L["TEXT_POS_X"] = "Text Position X"
L["TEXT_POS_Y"] = "Text Position Y"
L["TOGGLE_CASTBAR"] = "Enable Castbar"
L["TOGGLE_CASTBAR_TOOLTIP"] = "Enables or disables castbar for this specific unit frame."
L["WIDTH"] = "Castbar Width"
L["WIDTH_TOOLTIP"] = "Sets the castbar width."
