local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "ruRU")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

--@localization(locale="ruRU", format="lua_additive_table", handle-unlocalized="ignore")@
