local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "zhCN") 
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "自动调整施法条位置"
L["AUTO_POS_BAR_TOOLTIP"] = [=[勾选此选项时, 将会根据用户框体显示的增益效果及其他内容来自动调整位置.

注意: 可能不兼容第三方用户框体.]=]
L["BORDER_COLOR"] = "边框颜色"
L["CAST_BORDER"] = "边框纹理"
L["CAST_BORDER_TOOLTIP"] = "为施法条选择边框纹理."
L["CAST_FONT"] = "施法条字体"
L["CAST_FONT_TOOLTIP"] = "为法术名称和计时器文字选择字体类型."
L["CAST_STATUSBAR"] = "施法条纹理"
L["CAST_STATUSBAR_TOOLTIP"] = "为施法条/状态条选择纹理类型."
L["CASTBAR"] = "施法条"
L["CASTBAR_COLORS"] = "施法条颜色"
L["CASTBAR_ICON"] = "施法条图标"
L["CASTBAR_SIZING"] = "施法条大小"
L["CASTBAR_TEXTURE_FONT"] = "施法条纹理"
L["DEFAULT"] = "默认"
L["FONT_SIZE"] = "字体大小"
L["FONT_SIZE_TOOLTIP"] = "为法术名称和计时器文字选择字体类型."
L["GENERAL"] = "通用设置"
L["HEIGHT"] = "施法条高度"
L["HEIGHT_TOOLTIP"] = "设置施法条高度."
L["ICON_HIDE_BORDER"] = "隐藏图标边框"
L["ICON_POS_TOOLTIP"] = "为施法图标设置坐标值."
L["ICON_POS_X"] = "图标位置 X"
L["ICON_POS_Y"] = "图标位置 Y"
L["ICON_SIZE"] = "图标大小"
L["ICON_SIZE_TOOLTIP"] = "为施法条图标设置大小."
L["LSM_TEXTURE_NOTE"] = [=[

备注: 如果您使用了第三方纹理/字体, 并且随后删除了它们, 那么为了确保插件能够正常工作, 您必须手动在此重置它们.]=]
L["NAMEPLATE"] = "角色头顶姓名条"
L["PUSHBACK"] = "侦测施法延迟"
L["PUSHBACK_TOOLTIP"] = [=[为施法时受到攻击以及减益效果 (例如: 语言诅咒) 而造成的延迟启用侦测功能.

注意: 由于特定法术和天赋可能会忽略延迟, 故侦测到的延迟不完全准确, 仅供参考.
]=]
L["RESET_ALL"] = "重置所有设置"
L["SHOW_CAST_INFO_ONLY"] = "仅显示施法信息"
L["SHOW_CAST_INFO_ONLY_TOOLTIP"] = [=[启用将隐藏施法计时器, 但是仍然会显示施法信息.

如果您仅想显示施法名称而不是整个施法条, 则需要将施法条高度设置为 '0', 並且将边框设置为 '无'.]=]
L["SHOW_TIMER"] = "显示计时器文字"
L["SHOW_TIMER_TOOLTIP"] = "为当前的施法显示倒计时."
L["STATUS_CHANNEL_COLOR"] = "引导指示器填充颜色"
L["STATUS_COLOR"] = "施法指示器填充颜色"
L["TARGET"] = "目标"
L["TEST"] = "切换测试模式"
L["TEST_MODE_DRAG"] = "测试模式 - 拖动来调整施法条位置"
L["TEST_PLATE_TOOLTIP"] = [=[在角色头顶显示测试施法条, 以便于您可以拖动来调整位置.
注意: 您首先需要选择一个目标来让施法条显示出来, 才能看到测试施法条.
]=]
L["TEST_TARGET_TOOLTIP"] = [=[在目标框体上显示施法条, 以便于您可以拖动来调整位置.
注意: 您需要首先选择一个目标, 才能看到测试施法条.
]=]
L["TEXT_COLOR"] = "文字颜色"
L["TOGGLE_CASTBAR"] = "启用施法条"
L["TOGGLE_CASTBAR_TOOLTIP"] = "为当前框体启用/停用施法条."
L["WIDTH"] = "施法条宽度"
L["WIDTH_TOOLTIP"] = "设置施法条宽度."
