name: CI

on:
  push:
    tags:
      - "v*"
      - "!**-alpha**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --quiet

      - name: Create and deploy packages
        uses: BigWigsMods/packager@v2
        with:
          args: -w 24925
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
